/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppIcon: typeof import('./src/ui/base/AppIcon.vue')['default']
    AppPageShell: typeof import('./src/ui/layout/AppPageShell.vue')['default']
    AppTabs: typeof import('./src/ui/layout/AppTabs.vue')['default']
    AvatarCropDialog: typeof import('./src/ui/domain/avatar/AvatarCropDialog.vue')['default']
    BaseAvatar: typeof import('./src/ui/base/BaseAvatar.vue')['default']
    BaseButton: typeof import('./src/ui/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/ui/base/BaseCard.vue')['default']
    BaseConfirmDialog: typeof import('./src/ui/base/BaseConfirmDialog.vue')['default']
    BaseDialog: typeof import('./src/ui/base/BaseDialog.vue')['default']
    BaseIconButton: typeof import('./src/ui/base/BaseIconButton.vue')['default']
    BaseInput: typeof import('./src/ui/base/BaseInput.vue')['default']
    BaseLayout: typeof import('./src/ui/layout/BaseLayout.vue')['default']
    BaseList: typeof import('./src/ui/base/BaseList.vue')['default']
    BaseListItem: typeof import('./src/ui/base/BaseListItem.vue')['default']
    BaseMediaViewer: typeof import('./src/ui/base/BaseMediaViewer.vue')['default']
    BaseMenuItem: typeof import('./src/ui/base/BaseMenuItem.vue')['default']
    BasePill: typeof import('./src/ui/base/BasePill.vue')['default']
    BaseSelect: typeof import('./src/ui/base/BaseSelect.vue')['default']
    BaseToastViewport: typeof import('./src/ui/base/BaseToastViewport.vue')['default']
    GitHubIcon: typeof import('./src/ui/icons/GitHubIcon.vue')['default']
    PanelSectionHeader: typeof import('./src/ui/layout/PanelSectionHeader.vue')['default']
    QfacePenguinIcon: typeof import('./src/ui/icons/QfacePenguinIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowListItem: typeof import('./src/ui/base/RowListItem.vue')['default']
  }
}
