services:
  backend:
    container_name: iCinema_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
    environment:
      - PYTHONPATH=/workspace/backend
    init: true
    tty: true
    stdin_open: true
    restart: unless-stopped

  # frontend:
  #   container_name: iCinema_frontend
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - .:/workspace
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - backend
  #   tty: true
  #   restart: unless-stopped
    
    
