export type UnicodeEmojiCategory =
  | "faces"
  | "gestures"
  | "hearts"
  | "symbols"
  | "objects"
  | "nature"
  | "animals";

export type UnicodeEmojiDefinition = {
  id: string;
  char: string;
  labelEn: string;
  labelZh: string;
  category: UnicodeEmojiCategory;
};

export const unicodeEmojiCatalog: UnicodeEmojiDefinition[] = [
  { id: "grinning", char: "😀", labelEn: "grinning face", labelZh: "嘿嘿", category: "faces" },
  { id: "grin", char: "😁", labelEn: "beaming face with smiling eyes", labelZh: "嘻嘻", category: "faces" },
  { id: "joy", char: "😂", labelEn: "face with tears of joy", labelZh: "笑哭了", category: "faces" },
  { id: "rofl", char: "🤣", labelEn: "rolling on the floor laughing", labelZh: "笑得满地打滚", category: "faces" },
  { id: "smile", char: "😄", labelEn: "grinning face with smiling eyes", labelZh: "大笑", category: "faces" },
  { id: "sweat-smile", char: "😅", labelEn: "grinning face with sweat", labelZh: "苦笑", category: "faces" },
  { id: "wink", char: "😉", labelEn: "winking face", labelZh: "眨眼", category: "faces" },
  { id: "blush", char: "😊", labelEn: "smiling face with smiling eyes", labelZh: "羞涩微笑", category: "faces" },
  { id: "yum", char: "😋", labelEn: "face savoring food", labelZh: "好吃", category: "faces" },
  { id: "heart-eyes", char: "😍", labelEn: "smiling face with heart-eyes", labelZh: "花痴", category: "faces" },
  { id: "kiss", char: "😘", labelEn: "face blowing a kiss", labelZh: "飞吻", category: "faces" },
  { id: "thinking", char: "🤔", labelEn: "thinking face", labelZh: "想一想", category: "faces" },
  { id: "salute", char: "🫡", labelEn: "saluting face", labelZh: "敬礼", category: "faces" },
  { id: "zipper-mouth", char: "🤐", labelEn: "zipper-mouth face", labelZh: "闭嘴", category: "faces" },
  { id: "neutral", char: "😐", labelEn: "neutral face", labelZh: "冷漠", category: "faces" },
  { id: "expressionless", char: "😑", labelEn: "expressionless face", labelZh: "无语", category: "faces" },
  { id: "rolling-eyes", char: "🙄", labelEn: "face with rolling eyes", labelZh: "翻白眼", category: "faces" },
  { id: "smirk", char: "😏", labelEn: "smirking face", labelZh: "得意", category: "faces" },
  { id: "relieved", char: "😌", labelEn: "relieved face", labelZh: "释然", category: "faces" },
  { id: "sleepy", char: "😪", labelEn: "sleepy face", labelZh: "困", category: "faces" },
  { id: "sleeping", char: "😴", labelEn: "sleeping face", labelZh: "睡觉", category: "faces" },
  { id: "mask", char: "😷", labelEn: "face with medical mask", labelZh: "口罩", category: "faces" },
  { id: "woozy", char: "🥴", labelEn: "woozy face", labelZh: "头昏眼花", category: "faces" },
  { id: "mind-blown", char: "🤯", labelEn: "exploding head", labelZh: "脑袋爆炸", category: "faces" },
  { id: "melting", char: "🫠", labelEn: "melting face", labelZh: "融化", category: "faces" },
  { id: "pleading", char: "🥺", labelEn: "pleading face", labelZh: "恳求", category: "faces" },
  { id: "sob", char: "😭", labelEn: "loudly crying face", labelZh: "大哭", category: "faces" },
  { id: "angry", char: "😠", labelEn: "angry face", labelZh: "生气", category: "faces" },
  { id: "rage", char: "😡", labelEn: "pouting face", labelZh: "怒", category: "faces" },
  { id: "scream", char: "😱", labelEn: "face screaming in fear", labelZh: "尖叫", category: "faces" },
  { id: "party", char: "🥳", labelEn: "partying face", labelZh: "开派对", category: "faces" },
  { id: "cool", char: "😎", labelEn: "smiling face with sunglasses", labelZh: "墨镜", category: "faces" },
  { id: "nerd", char: "🤓", labelEn: "nerd face", labelZh: "书呆子", category: "faces" },
  { id: "clown", char: "🤡", labelEn: "clown face", labelZh: "小丑", category: "faces" },
  { id: "ghost", char: "👻", labelEn: "ghost", labelZh: "鬼", category: "faces" },
  { id: "skull", char: "💀", labelEn: "skull", labelZh: "骷髅", category: "faces" },
  { id: "robot", char: "🤖", labelEn: "robot", labelZh: "机器人", category: "faces" },
  { id: "poop", char: "💩", labelEn: "pile of poo", labelZh: "便便", category: "faces" },

  { id: "wave", char: "👋", labelEn: "waving hand", labelZh: "挥手", category: "gestures" },
  { id: "raised-back", char: "🤚", labelEn: "raised back of hand", labelZh: "举起手背", category: "gestures" },
  { id: "raised-hand", char: "✋", labelEn: "raised hand", labelZh: "举手", category: "gestures" },
  { id: "v", char: "✌️", labelEn: "victory hand", labelZh: "胜利手势", category: "gestures" },
  { id: "crossed-fingers", char: "🤞", labelEn: "crossed fingers", labelZh: "交叉手指", category: "gestures" },
  { id: "love-you", char: "🤟", labelEn: "love-you gesture", labelZh: "爱你手势", category: "gestures" },
  { id: "ok-hand", char: "👌", labelEn: "OK hand", labelZh: "OK手势", category: "gestures" },
  { id: "pinched-fingers", char: "🤌", labelEn: "pinched fingers", labelZh: "捏手指", category: "gestures" },
  { id: "pinching-hand", char: "🤏", labelEn: "pinching hand", labelZh: "捏", category: "gestures" },
  { id: "thumbs-up", char: "👍", labelEn: "thumbs up", labelZh: "赞", category: "gestures" },
  { id: "thumbs-down", char: "👎", labelEn: "thumbs down", labelZh: "踩", category: "gestures" },
  { id: "fist", char: "✊", labelEn: "raised fist", labelZh: "握拳", category: "gestures" },
  { id: "punch", char: "👊", labelEn: "oncoming fist", labelZh: "出拳", category: "gestures" },
  { id: "clap", char: "👏", labelEn: "clapping hands", labelZh: "鼓掌", category: "gestures" },
  { id: "pray", char: "🙏", labelEn: "folded hands", labelZh: "双手合十", category: "gestures" },
  { id: "muscle", char: "💪", labelEn: "flexed biceps", labelZh: "肌肉", category: "gestures" },
  { id: "writing", char: "✍️", labelEn: "writing hand", labelZh: "写字", category: "gestures" },

  { id: "heart", char: "❤️", labelEn: "red heart", labelZh: "红心", category: "hearts" },
  { id: "pink-heart", char: "🩷", labelEn: "pink heart", labelZh: "粉心", category: "hearts" },
  { id: "orange-heart", char: "🧡", labelEn: "orange heart", labelZh: "橙心", category: "hearts" },
  { id: "yellow-heart", char: "💛", labelEn: "yellow heart", labelZh: "黄心", category: "hearts" },
  { id: "green-heart", char: "💚", labelEn: "green heart", labelZh: "绿心", category: "hearts" },
  { id: "blue-heart", char: "💙", labelEn: "blue heart", labelZh: "蓝心", category: "hearts" },
  { id: "purple-heart", char: "💜", labelEn: "purple heart", labelZh: "紫心", category: "hearts" },
  { id: "brown-heart", char: "🤎", labelEn: "brown heart", labelZh: "棕心", category: "hearts" },
  { id: "black-heart", char: "🖤", labelEn: "black heart", labelZh: "黑心", category: "hearts" },
  { id: "white-heart", char: "🤍", labelEn: "white heart", labelZh: "白心", category: "hearts" },
  { id: "heart-fire", char: "❤️‍🔥", labelEn: "heart on fire", labelZh: "燃烧的心", category: "hearts" },
  { id: "mending-heart", char: "❤️‍🩹", labelEn: "mending heart", labelZh: "包扎的心", category: "hearts" },
  { id: "sparkling-heart", char: "💖", labelEn: "sparkling heart", labelZh: "闪亮的心", category: "hearts" },
  { id: "growing-heart", char: "💗", labelEn: "growing heart", labelZh: "不断长大的心", category: "hearts" },
  { id: "beating-heart", char: "💓", labelEn: "beating heart", labelZh: "怦然心动", category: "hearts" },
  { id: "two-hearts", char: "💕", labelEn: "two hearts", labelZh: "两颗心", category: "hearts" },
  { id: "broken-heart", char: "💔", labelEn: "broken heart", labelZh: "心碎", category: "hearts" },

  { id: "sparkles", char: "✨", labelEn: "sparkles", labelZh: "火花", category: "symbols" },
  { id: "fire", char: "🔥", labelEn: "fire", labelZh: "火", category: "symbols" },
  { id: "hundred", char: "💯", labelEn: "hundred points", labelZh: "一百分", category: "symbols" },
  { id: "collision", char: "💥", labelEn: "collision", labelZh: "撞击", category: "symbols" },
  { id: "sweat-drops", char: "💦", labelEn: "sweat droplets", labelZh: "汗滴", category: "symbols" },
  { id: "dizzy", char: "💫", labelEn: "dizzy", labelZh: "头晕", category: "symbols" },
  { id: "star", char: "⭐", labelEn: "star", labelZh: "星星", category: "symbols" },
  { id: "glowing-star", char: "🌟", labelEn: "glowing star", labelZh: "发光的星星", category: "symbols" },
  { id: "boom", char: "🧨", labelEn: "firecracker", labelZh: "鞭炮", category: "symbols" },
  { id: "check", char: "✅", labelEn: "check mark button", labelZh: "对勾按钮", category: "symbols" },
  { id: "cross-mark", char: "❌", labelEn: "cross mark", labelZh: "叉", category: "symbols" },
  { id: "warning", char: "⚠️", labelEn: "warning", labelZh: "警告", category: "symbols" },
  { id: "question", char: "❓", labelEn: "question mark", labelZh: "问号", category: "symbols" },
  { id: "exclamation", char: "❗", labelEn: "exclamation mark", labelZh: "感叹号", category: "symbols" },
  { id: "zzz", char: "💤", labelEn: "zzz", labelZh: "睡眠", category: "symbols" },
  { id: "eyes", char: "👀", labelEn: "eyes", labelZh: "眼睛", category: "symbols" },
  { id: "brain", char: "🧠", labelEn: "brain", labelZh: "大脑", category: "symbols" },

  { id: "music", char: "🎵", labelEn: "musical note", labelZh: "音符", category: "objects" },
  { id: "headphones", char: "🎧", labelEn: "headphone", labelZh: "耳机", category: "objects" },
  { id: "microphone", char: "🎤", labelEn: "microphone", labelZh: "麦克风", category: "objects" },
  { id: "movie", char: "🎬", labelEn: "clapper board", labelZh: "场记板", category: "objects" },
  { id: "camera", char: "📷", labelEn: "camera", labelZh: "相机", category: "objects" },
  { id: "tv", char: "📺", labelEn: "television", labelZh: "电视", category: "objects" },
  { id: "phone", char: "📱", labelEn: "mobile phone", labelZh: "手机", category: "objects" },
  { id: "computer", char: "💻", labelEn: "laptop", labelZh: "笔记本电脑", category: "objects" },
  { id: "light-bulb", char: "💡", labelEn: "light bulb", labelZh: "灯泡", category: "objects" },
  { id: "popcorn", char: "🍿", labelEn: "popcorn", labelZh: "爆米花", category: "objects" },
  { id: "coffee", char: "☕", labelEn: "hot beverage", labelZh: "热饮", category: "objects" },
  { id: "cake", char: "🎂", labelEn: "birthday cake", labelZh: "生日蛋糕", category: "objects" },
  { id: "gift", char: "🎁", labelEn: "wrapped gift", labelZh: "礼物", category: "objects" },
  { id: "trophy", char: "🏆", labelEn: "trophy", labelZh: "奖杯", category: "objects" },
  { id: "rocket", char: "🚀", labelEn: "rocket", labelZh: "火箭", category: "objects" },

  { id: "sun", char: "☀️", labelEn: "sun", labelZh: "太阳", category: "nature" },
  { id: "moon", char: "🌙", labelEn: "crescent moon", labelZh: "月牙", category: "nature" },
  { id: "rainbow", char: "🌈", labelEn: "rainbow", labelZh: "彩虹", category: "nature" },
  { id: "cloud", char: "☁️", labelEn: "cloud", labelZh: "云", category: "nature" },
  { id: "snowflake", char: "❄️", labelEn: "snowflake", labelZh: "雪花", category: "nature" },
  { id: "sunflower", char: "🌻", labelEn: "sunflower", labelZh: "向日葵", category: "nature" },
  { id: "tulip", char: "🌷", labelEn: "tulip", labelZh: "郁金香", category: "nature" },
  { id: "rose", char: "🌹", labelEn: "rose", labelZh: "玫瑰", category: "nature" },
  { id: "leaves", char: "🍃", labelEn: "leaf fluttering in wind", labelZh: "风中的树叶", category: "nature" },
  { id: "cherry-blossom", char: "🌸", labelEn: "cherry blossom", labelZh: "樱花", category: "nature" },
  { id: "cat-face", char: "🐱", labelEn: "cat face", labelZh: "猫脸", category: "animals" },
  { id: "cat", char: "🐈", labelEn: "cat", labelZh: "猫", category: "animals" },
  { id: "dog-face", char: "🐶", labelEn: "dog face", labelZh: "狗脸", category: "animals" },
  { id: "dog", char: "🐕", labelEn: "dog", labelZh: "狗", category: "animals" },
  { id: "pig-face", char: "🐷", labelEn: "pig face", labelZh: "猪脸", category: "animals" },
  { id: "pig", char: "🐖", labelEn: "pig", labelZh: "猪", category: "animals" },
  { id: "panda", char: "🐼", labelEn: "panda", labelZh: "熊猫", category: "animals" },
  { id: "penguin", char: "🐧", labelEn: "penguin", labelZh: "企鹅", category: "animals" },
  { id: "spouting-whale", char: "🐳", labelEn: "spouting whale", labelZh: "喷水鲸", category: "animals" },
  { id: "whale", char: "🐋", labelEn: "whale", labelZh: "鲸鱼", category: "animals" },
];
