"""initial schema

Revision ID: 01bf66a2961c
Revises: 
Create Date: 2026-04-15 02:14:41.334463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '01bf66a2961c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('avatar_key', sa.String(length=255), nullable=True),
    sa.Column('auto_accept', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_type', 'storage_key', name='uq_media_assets_asset_type_storage_key')
    )
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_assets_asset_type'), ['asset_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_sha256'), ['sha256'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_assets_uploaded_by_user_id'), ['uploaded_by_user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('related_type', sa.String(length=64), nullable=True),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_notification_type'), ['notification_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_user_id'), ['recipient_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_id'), ['related_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_type'), ['related_type'], unique=False)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='private', nullable=False),
    sa.Column('join_audit_mode', sa.String(length=32), server_default='manual_review', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_join_audit_mode'), ['join_audit_mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rooms_visibility'), ['visibility'], unique=False)

    op.create_table('user_emoji_usages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), server_default='qface', nullable=False),
    sa.Column('emoji_id', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', 'emoji_id', name='uq_user_emoji_usages_user_provider_emoji')
    )
    with op.batch_alter_table('user_emoji_usages', schema=None) as batch_op:
        batch_op.create_index('idx_user_emoji_usages_emoji_id', ['emoji_id'], unique=False)
        batch_op.create_index('idx_user_emoji_usages_user_id_last_used_at', ['user_id', 'last_used_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_emoji_usages_user_id'), ['user_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sender_user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_user_id'), ['sender_user_id'], unique=False)

    op.create_table('room_join_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('room_action', sa.String(length=16), nullable=False),
    sa.Column('target_action', sa.String(length=16), nullable=False),
    sa.Column('room_action_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_action_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_join_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_join_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_initiator_user_id'), ['initiator_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_room_action_by_user_id'), ['room_action_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_join_requests_target_user_id'), ['target_user_id'], unique=False)

    op.create_table('room_members',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.create_table('room_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('selected_room_video_source_type', sa.String(length=32), server_default='external_url', nullable=False),
    sa.Column('sync_policy', sa.String(length=32), server_default='auto_sync', nullable=False),
    sa.Column('active_sync_permission', sa.String(length=32), server_default='owner_and_manager', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('room_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_room_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_room_settings_room_id'), ['room_id'], unique=True)

    op.create_table('user_avatar_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_avatar_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_avatar_assets_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_avatar_assets_user_id'), ['user_id'], unique=False)

    op.create_table('user_sticker_library_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'media_asset_id', name='uq_user_sticker_library_user_asset')
    )
    with op.batch_alter_table('user_sticker_library_items', schema=None) as batch_op:
        batch_op.create_index('idx_user_sticker_library_user_id_created_at', ['user_id', 'created_at'], unique=False)
        batch_op.create_index('idx_user_sticker_library_user_id_sort_order_created_at', ['user_id', 'sort_order', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sticker_library_items_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sticker_library_items_user_id'), ['user_id'], unique=False)

    op.create_table('message_resource_refs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('media_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'media_asset_id', name='uq_message_resource_refs_message_asset')
    )
    with op.batch_alter_table('message_resource_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_resource_refs_media_asset_id'), ['media_asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_resource_refs_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_resource_refs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_resource_refs_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_resource_refs_media_asset_id'))

    op.drop_table('message_resource_refs')
    with op.batch_alter_table('user_sticker_library_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sticker_library_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sticker_library_items_media_asset_id'))
        batch_op.drop_index('idx_user_sticker_library_user_id_sort_order_created_at')
        batch_op.drop_index('idx_user_sticker_library_user_id_created_at')

    op.drop_table('user_sticker_library_items')
    with op.batch_alter_table('user_avatar_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_avatar_assets_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_avatar_assets_media_asset_id'))

    op.drop_table('user_avatar_assets')
    with op.batch_alter_table('room_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_settings_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_settings_id'))

    op.drop_table('room_settings')
    op.drop_table('room_members')
    with op.batch_alter_table('room_join_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_room_join_requests_target_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_status'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_source'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_room_id'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_room_action_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_initiator_user_id'))
        batch_op.drop_index(batch_op.f('ix_room_join_requests_id'))

    op.drop_table('room_join_requests')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_user_id'))
        batch_op.drop_index(batch_op.f('ix_messages_room_id'))
        batch_op.drop_index(batch_op.f('ix_messages_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    op.drop_table('messages')
    with op.batch_alter_table('user_emoji_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_emoji_usages_user_id'))
        batch_op.drop_index('idx_user_emoji_usages_user_id_last_used_at')
        batch_op.drop_index('idx_user_emoji_usages_emoji_id')

    op.drop_table('user_emoji_usages')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_visibility'))
        batch_op.drop_index(batch_op.f('ix_rooms_owner_id'))
        batch_op.drop_index(batch_op.f('ix_rooms_join_audit_mode'))
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_related_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_related_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_notification_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index(batch_op.f('ix_notifications_actor_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('media_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_assets_uploaded_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_media_assets_sha256'))
        batch_op.drop_index(batch_op.f('ix_media_assets_asset_type'))

    op.drop_table('media_assets')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
