"""change icon_path to avatar_path

Revision ID: da9bc32002e1
Revises: 24009582185e
Create Date: 2025-06-12 16:29:18.507795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da9bc32002e1'
down_revision: Union[str, None] = '24009582185e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    op.drop_column('users', 'icon_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon_path', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
