/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/ui/layouts/components/AppHeader.vue')['default']
    AppIcon: typeof import('./src/ui/base/AppIcon.vue')['default']
    AppLayout: typeof import('./src/ui/layouts/AppLayout.vue')['default']
    AppPageShell: typeof import('./src/ui/layout/AppPageShell.vue')['default']
    AppSidebar: typeof import('./src/ui/layouts/components/AppSidebar.vue')['default']
    AuthLayout: typeof import('./src/ui/layouts/AuthLayout.vue')['default']
    AvatarCropDialog: typeof import('./src/ui/domain/avatar/AvatarCropDialog.vue')['default']
    BaseAvatar: typeof import('./src/ui/base/BaseAvatar.vue')['default']
    BaseButton: typeof import('./src/ui/base/BaseButton.vue')['default']
    BaseCard: typeof import('./src/ui/base/BaseCard.vue')['default']
    BaseConfirmDialog: typeof import('./src/ui/base/BaseConfirmDialog.vue')['default']
    BaseDialog: typeof import('./src/ui/base/BaseDialog.vue')['default']
    BaseIconButton: typeof import('./src/ui/base/BaseIconButton.vue')['default']
    BaseInput: typeof import('./src/ui/base/BaseInput.vue')['default']
    BaseLayout: typeof import('./src/ui/layout/BaseLayout.vue')['default']
    BaseList: typeof import('./src/ui/base/BaseList.vue')['default']
    BaseListItem: typeof import('./src/ui/base/BaseListItem.vue')['default']
    BaseMenuItem: typeof import('./src/ui/base/BaseMenuItem.vue')['default']
    BaseSelect: typeof import('./src/ui/base/BaseSelect.vue')['default']
    BaseToast: typeof import('./src/ui/base/BaseToast.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RowListItem: typeof import('./src/ui/base/RowListItem.vue')['default']
  }
}
