// 常用emoji表情数据
export const EMOJI_CATEGORIES = {
  smileys: {
    name: '笑脸',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: '开心大笑' },
      { emoji: '😃', name: '咧嘴笑' },
      { emoji: '😄', name: '眯眼笑' },
      { emoji: '😁', name: '露齿笑' },
      { emoji: '😆', name: '挤眉弄眼' },
      { emoji: '😅', name: '苦笑' },
      { emoji: '🤣', name: '大笑到流泪' },
      { emoji: '😂', name: '喜极而泣' },
      { emoji: '🙂', name: '微笑' },
      { emoji: '🙃', name: '颠倒笑脸' },
      { emoji: '😉', name: '眨眼' },
      { emoji: '😊', name: '害羞微笑' },
      { emoji: '😇', name: '天使笑脸' },
      { emoji: '🥰', name: '恋爱脸' },
      { emoji: '😍', name: '心形眼' },
      { emoji: '🤩', name: '星星眼' },
      { emoji: '😘', name: '飞吻' },
      { emoji: '😗', name: '亲吻脸' },
      { emoji: '😚', name: '闭眼亲吻' },
      { emoji: '😙', name: '微笑亲吻' },
      { emoji: '🥲', name: '含泪微笑' },
      { emoji: '😋', name: '舔嘴唇' },
      { emoji: '😛', name: '吐舌头' },
      { emoji: '😜', name: '调皮眨眼' },
      { emoji: '🤪', name: '疯狂脸' },
      { emoji: '😝', name: '紧闭眼吐舌' },
      { emoji: '🤑', name: '财迷脸' },
      { emoji: '🤗', name: '拥抱脸' },
      { emoji: '🤭', name: '偷笑' },
      { emoji: '🤫', name: '嘘' },
      { emoji: '🤔', name: '思考' },
      { emoji: '🤐', name: '拉链嘴' },
      { emoji: '🤨', name: '挑眉' },
      { emoji: '😐', name: '面无表情' },
      { emoji: '😑', name: '无语' },
      { emoji: '😶', name: '没有嘴' },
      { emoji: '🫥', name: '虚线脸' },
      { emoji: '😒', name: '不爽' },
      { emoji: '🙄', name: '翻白眼' },
      { emoji: '😬', name: '咧嘴苦笑' },
      { emoji: '😮‍💨', name: '呼气' },
      { emoji: '🤥', name: '撒谎' },
      { emoji: '😴', name: '睡觉' },
      { emoji: '😪', name: '困倦' },
      { emoji: '😵', name: '晕' },
      { emoji: '😵‍💫', name: '头晕眼花' },
      { emoji: '🤤', name: '流口水' },
      { emoji: '😷', name: '戴口罩' },
      { emoji: '🤒', name: '发烧' },
      { emoji: '🤕', name: '受伤' },
      { emoji: '🤢', name: '恶心' },
      { emoji: '🤮', name: '呕吐' },
      { emoji: '🤧', name: '打喷嚏' },
      { emoji: '🥵', name: '热' },
      { emoji: '🥶', name: '冷' },
      { emoji: '🥴', name: '醉酒' },
      { emoji: '😵', name: '眩晕' },
      { emoji: '🤯', name: '爆炸头' },
      { emoji: '🤠', name: '牛仔' },
      { emoji: '🥳', name: '庆祝' },
      { emoji: '🥸', name: '伪装' },
      { emoji: '😎', name: '墨镜酷' },
      { emoji: '🤓', name: '书呆子' },
      { emoji: '🧐', name: '单片眼镜' },
      { emoji: '😕', name: '失望' },
      { emoji: '😟', name: '担心' },
      { emoji: '🙁', name: '轻微皱眉' },
      { emoji: '☹️', name: '皱眉' },
      { emoji: '😮', name: '惊讶张嘴' },
      { emoji: '😯', name: '沉默惊讶' },
      { emoji: '😲', name: '震惊' },
      { emoji: '😳', name: '脸红' },
      { emoji: '🥺', name: '恳求' },
      { emoji: '😦', name: '皱眉张嘴' },
      { emoji: '😧', name: '痛苦' },
      { emoji: '😨', name: '恐惧' },
      { emoji: '😰', name: '焦虑冒汗' },
      { emoji: '😥', name: '失望但释然' },
      { emoji: '😢', name: '哭泣' },
      { emoji: '😭', name: '大哭' },
      { emoji: '😱', name: '恐惧尖叫' },
      { emoji: '😖', name: '困惑' },
      { emoji: '😣', name: '坚持' },
      { emoji: '😞', name: '失望' },
      { emoji: '😓', name: '冷汗' },
      { emoji: '😩', name: '疲惫' },
      { emoji: '😫', name: '疲惫哭泣' },
      { emoji: '🥱', name: '打哈欠' },
      { emoji: '😤', name: '哼气' },
      { emoji: '😡', name: '愤怒红脸' },
      { emoji: '😠', name: '生气' },
      { emoji: '🤬', name: '爆粗口' },
      { emoji: '😈', name: '恶魔笑' },
      { emoji: '👿', name: '愤怒恶魔' },
      { emoji: '💀', name: '骷髅头' },
      { emoji: '☠️', name: '骷髅交叉骨' },
      { emoji: '💩', name: '便便' },
      { emoji: '🤡', name: '小丑' },
      { emoji: '👹', name: '日式恶魔' },
      { emoji: '👺', name: '日式妖怪' },
      { emoji: '👻', name: '幽灵' },
      { emoji: '👽', name: '外星人' },
      { emoji: '👾', name: '像素外星人' },
      { emoji: '🤖', name: '机器人' },
      { emoji: '😺', name: '开心猫咪' },
      { emoji: '😸', name: '笑眯眯猫' },
      { emoji: '😹', name: '喜极而泣猫' },
      { emoji: '😻', name: '心形眼猫' },
      { emoji: '😼', name: '得意猫' },
      { emoji: '😽', name: '亲吻猫' },
      { emoji: '🙀', name: '恐惧猫' },
      { emoji: '😿', name: '哭泣猫' },
      { emoji: '😾', name: '愤怒猫' }
    ]
  },
  hearts: {
    name: '心形',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: '红心' },
      { emoji: '🧡', name: '橙心' },
      { emoji: '💛', name: '黄心' },
      { emoji: '💚', name: '绿心' },
      { emoji: '💙', name: '蓝心' },
      { emoji: '💜', name: '紫心' },
      { emoji: '🖤', name: '黑心' },
      { emoji: '🤍', name: '白心' },
      { emoji: '🤎', name: '棕心' },
      { emoji: '💔', name: '心碎' },
      { emoji: '❣️', name: '心形感叹号' },
      { emoji: '💕', name: '两颗粉心' },
      { emoji: '💞', name: '旋转的心' },
      { emoji: '💓', name: '心跳' },
      { emoji: '💗', name: '成长的心' },
      { emoji: '💖', name: '闪闪发光的心' },
      { emoji: '💘', name: '丘比特之箭' },
      { emoji: '💝', name: '礼品盒心' },
      { emoji: '💟', name: '心形装饰' },
      { emoji: '♥️', name: '红心套装' }
    ]
  },
  gestures: {
    name: '手势',
    icon: '👍',
    emojis: [
      { emoji: '👍', name: '点赞' },
      { emoji: '👎', name: '踩' },
      { emoji: '👌', name: 'OK手势' },
      { emoji: '🤌', name: '捏手指' },
      { emoji: '🤏', name: '捏着' },
      { emoji: '✌️', name: '胜利手势' },
      { emoji: '🤞', name: '交叉手指' },
      { emoji: '🤟', name: '我爱你手势' },
      { emoji: '🤘', name: '摇滚手势' },
      { emoji: '🤙', name: '打电话手势' },
      { emoji: '👈', name: '向左指' },
      { emoji: '👉', name: '向右指' },
      { emoji: '👆', name: '向上指' },
      { emoji: '🖕', name: '竖中指' },
      { emoji: '👇', name: '向下指' },
      { emoji: '☝️', name: '食指向上' },
      { emoji: '👋', name: '挥手' },
      { emoji: '🤚', name: '抬手背' },
      { emoji: '🖐️', name: '张开手' },
      { emoji: '✋', name: '停' },
      { emoji: '🖖', name: '瓦肯举手礼' },
      { emoji: '👏', name: '鼓掌' },
      { emoji: '🙌', name: '举双手庆祝' },
      { emoji: '🤲', name: '托举手势' },
      { emoji: '🤝', name: '握手' },
      { emoji: '🙏', name: '祈祷/感谢' },
      { emoji: '✍️', name: '写字' },
      { emoji: '💪', name: '肌肉' },
      { emoji: '🦾', name: '机械臂' },
      { emoji: '🦿', name: '机械腿' }
    ]
  },
  people: {
    name: '人物',
    icon: '👤',
    emojis: [
      { emoji: '🧠', name: '大脑' },
      { emoji: '🫀', name: '心脏' },
      { emoji: '🫁', name: '肺' },
      { emoji: '🦷', name: '牙齿' },
      { emoji: '🦴', name: '骨头' },
      { emoji: '👀', name: '眼睛' },
      { emoji: '👁️', name: '单眼' },
      { emoji: '👅', name: '舌头' },
      { emoji: '👄', name: '嘴唇' },
      { emoji: '👶', name: '婴儿' },
      { emoji: '🧒', name: '儿童' },
      { emoji: '👦', name: '男孩' },
      { emoji: '👧', name: '女孩' },
      { emoji: '🧑', name: '成人' },
      { emoji: '👱', name: '金发人' },
      { emoji: '👨', name: '男人' },
      { emoji: '🧔', name: '有胡子的男人' },
      { emoji: '👩', name: '女人' },
      { emoji: '🧓', name: '老人' },
      { emoji: '👴', name: '老爷爷' },
      { emoji: '👵', name: '老奶奶' },
      { emoji: '🙍', name: '皱眉的人' },
      { emoji: '🙎', name: '撅嘴的人' },
      { emoji: '🙅', name: '不行手势' },
      { emoji: '🙆', name: 'OK手势' },
      { emoji: '💁', name: '服务台' },
      { emoji: '🙋', name: '举手' },
      { emoji: '🧏', name: '聋人' },
      { emoji: '🙇', name: '鞠躬' },
      { emoji: '🤦', name: '捂脸' }
    ]
  },
  animals: {
    name: '动物',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: '小狗' },
      { emoji: '🐱', name: '小猫' },
      { emoji: '🐭', name: '老鼠' },
      { emoji: '🐹', name: '仓鼠' },
      { emoji: '🐰', name: '兔子' },
      { emoji: '🦊', name: '狐狸' },
      { emoji: '🐻', name: '熊' },
      { emoji: '🐼', name: '熊猫' },
      { emoji: '🐨', name: '考拉' },
      { emoji: '🐯', name: '老虎' },
      { emoji: '🦁', name: '狮子' },
      { emoji: '🐮', name: '牛' },
      { emoji: '🐷', name: '猪' },
      { emoji: '🐽', name: '猪鼻子' },
      { emoji: '🐸', name: '青蛙' },
      { emoji: '🐵', name: '猴子' },
      { emoji: '🙈', name: '非礼勿视' },
      { emoji: '🙉', name: '非礼勿听' },
      { emoji: '🙊', name: '非礼勿言' },
      { emoji: '🐒', name: '猴脸' },
      { emoji: '🐔', name: '鸡' },
      { emoji: '🐧', name: '企鹅' },
      { emoji: '🐦', name: '鸟' },
      { emoji: '🐤', name: '小鸡' },
      { emoji: '🐣', name: '破壳小鸡' },
      { emoji: '🐥', name: '刚出壳小鸡' },
      { emoji: '🦆', name: '鸭子' },
      { emoji: '🦅', name: '老鹰' },
      { emoji: '🦉', name: '猫头鹰' },
      { emoji: '🦇', name: '蝙蝠' }
    ]
  },
  food: {
    name: '食物',
    icon: '🍎',
    emojis: [
      { emoji: '🍎', name: '苹果' },
      { emoji: '🍐', name: '梨' },
      { emoji: '🍊', name: '橘子' },
      { emoji: '🍋', name: '柠檬' },
      { emoji: '🍌', name: '香蕉' },
      { emoji: '🍉', name: '西瓜' },
      { emoji: '🍇', name: '葡萄' },
      { emoji: '🍓', name: '草莓' },
      { emoji: '🫐', name: '蓝莓' },
      { emoji: '🍈', name: '甜瓜' },
      { emoji: '🍒', name: '樱桃' },
      { emoji: '🍑', name: '桃子' },
      { emoji: '🥭', name: '芒果' },
      { emoji: '🍍', name: '菠萝' },
      { emoji: '🥥', name: '椰子' },
      { emoji: '🥝', name: '猕猴桃' },
      { emoji: '🍅', name: '番茄' },
      { emoji: '🍆', name: '茄子' },
      { emoji: '🥑', name: '牛油果' },
      { emoji: '🥦', name: '西兰花' },
      { emoji: '🥬', name: '生菜' },
      { emoji: '🥒', name: '黄瓜' },
      { emoji: '🌶️', name: '辣椒' },
      { emoji: '🫑', name: '甜椒' },
      { emoji: '🌽', name: '玉米' },
      { emoji: '🥕', name: '胡萝卜' },
      { emoji: '🫒', name: '橄榄' },
      { emoji: '🧄', name: '大蒜' },
      { emoji: '🧅', name: '洋葱' },
      { emoji: '🥔', name: '土豆' }
    ]
  },
  activities: {
    name: '活动',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: '足球' },
      { emoji: '🏀', name: '篮球' },
      { emoji: '🏈', name: '美式足球' },
      { emoji: '⚾', name: '棒球' },
      { emoji: '🥎', name: '垒球' },
      { emoji: '🎾', name: '网球' },
      { emoji: '🏐', name: '排球' },
      { emoji: '🏉', name: '橄榄球' },
      { emoji: '🥏', name: '飞盘' },
      { emoji: '🎱', name: '台球' },
      { emoji: '🪀', name: '悠悠球' },
      { emoji: '🏓', name: '乒乓球' },
      { emoji: '🏸', name: '羽毛球' },
      { emoji: '🏒', name: '冰球' },
      { emoji: '🏑', name: '曲棍球' },
      { emoji: '🥍', name: '长曲棍球' },
      { emoji: '🏏', name: '板球' },
      { emoji: '🪃', name: '回旋镖' },
      { emoji: '🥅', name: '球门' },
      { emoji: '⛳', name: '高尔夫旗' },
      { emoji: '🪁', name: '风筝' },
      { emoji: '🏹', name: '弓箭' },
      { emoji: '🎣', name: '钓鱼' },
      { emoji: '🤿', name: '潜水' },
      { emoji: '🥊', name: '拳击' },
      { emoji: '🥋', name: '武术' },
      { emoji: '🎽', name: '跑步衫' },
      { emoji: '🛹', name: '滑板' },
      { emoji: '🛷', name: '雪橇' },
      { emoji: '⛸️', name: '滑冰' }
    ]
  },
  symbols: {
    name: '符号',
    icon: '⭐',
    emojis: [
      { emoji: '⭐', name: '星星' },
      { emoji: '🌟', name: '闪亮的星' },
      { emoji: '💫', name: '流星' },
      { emoji: '✨', name: '闪光' },
      { emoji: '⚡', name: '闪电' },
      { emoji: '💥', name: '爆炸' },
      { emoji: '💢', name: '愤怒' },
      { emoji: '💨', name: '疾风' },
      { emoji: '💤', name: '睡觉' },
      { emoji: '💦', name: '汗珠' },
      { emoji: '💧', name: '水滴' },
      { emoji: '🌊', name: '海浪' },
      { emoji: '🔥', name: '火' },
      { emoji: '❄️', name: '雪花' },
      { emoji: '☀️', name: '太阳' },
      { emoji: '🌤️', name: '晴转多云' },
      { emoji: '⛅', name: '多云' },
      { emoji: '🌦️', name: '阵雨' },
      { emoji: '🌧️', name: '下雨' },
      { emoji: '⛈️', name: '雷雨' },
      { emoji: '🌩️', name: '闪电云' },
      { emoji: '🌨️', name: '下雪' },
      { emoji: '☁️', name: '云' },
      { emoji: '🌪️', name: '龙卷风' },
      { emoji: '🌈', name: '彩虹' },
      { emoji: '☂️', name: '雨伞' },
      { emoji: '☔', name: '雨滴伞' },
      { emoji: '⚠️', name: '警告' },
      { emoji: '🚫', name: '禁止' },
      { emoji: '✅', name: '完成' }
    ]
  }
};

export const EMOJI_PER_PAGE = 32;
