from enum import StrEnum


class ErrorReason(StrEnum):
    APP_ERROR = "app_error"

    AUTHENTICATION_REQUIRED = "authentication_required"
    EMAIL_ALREADY_EXISTS = "email_already_exists"
    INVALID_CREDENTIALS = "invalid_credentials"
    INVALID_REFRESH_TOKEN = "invalid_refresh_token"
    INVALID_TOKEN = "invalid_token"
    INVALID_TOKEN_PAYLOAD = "invalid_token_payload"
    INVALID_TOKEN_TYPE = "invalid_token_type"
    MISSING_AUTHORIZATION_TOKEN = "missing_authorization_token"
    USER_NOT_FOUND = "user_not_found"
    SITE_PERMISSION_DENIED = "site_permission_denied"

    CANNOT_REMOVE_SELF_FROM_ROOM = "cannot_remove_self_from_room"
    INVALID_ROOM_ID = "invalid_room_id"
    INVALID_ROOM_MEMBER_ROLE = "invalid_room_member_role"
    JOIN_REQUEST_ALREADY_HANDLED = "join_request_already_handled"
    JOIN_REQUEST_NOT_FOUND = "join_request_not_found"
    JOIN_REQUEST_TARGET_ACTION_FORBIDDEN = "join_request_target_action_forbidden"
    MISSING_ROOM_ID = "missing_room_id"
    OWNER_CANNOT_BE_REMOVED_FROM_ROOM = "owner_cannot_be_removed_from_room"
    OWNER_CANNOT_LEAVE_ROOM = "owner_cannot_leave_room"
    OWNER_ROLE_CANNOT_BE_CHANGED = "owner_role_cannot_be_changed"
    PENDING_JOIN_REQUEST_ALREADY_EXISTS = "pending_join_request_already_exists"
    ROOM_ENTER_FORBIDDEN = "room_enter_forbidden"
    ROOM_MEMBER_NOT_FOUND = "room_member_not_found"
    ROOM_NOT_ACCEPTING_JOIN_REQUESTS = "room_not_accepting_join_requests"
    ROOM_NOT_ENTERED = "room_not_entered"
    ROOM_NOT_FOUND = "room_not_found"
    ROOM_PERMISSION_DENIED = "room_permission_denied"
    ROOM_SETTINGS_NOT_FOUND = "room_settings_not_found"
    USER_ALREADY_ROOM_MEMBER = "user_already_room_member"

    DUPLICATE_STICKER_IDS = "duplicate_sticker_ids"
    EMPTY_AVATAR_FILE = "empty_avatar_file"
    EMPTY_MEDIA_FILE = "empty_media_file"
    IMAGE_NOT_FOUND = "image_not_found"
    IMAGE_UNAVAILABLE = "image_unavailable"
    INVALID_EMOJI_ID = "invalid_emoji_id"
    INVALID_IMAGE_ID = "invalid_image_id"
    INVALID_MEDIA_STORAGE_KEY = "invalid_media_storage_key"
    INVALID_STICKER_ID = "invalid_sticker_id"
    MEDIA_ASSET_NOT_FOUND = "media_asset_not_found"
    MEDIA_FILE_NOT_FOUND = "media_file_not_found"
    PAGINATION_NOT_ALLOWED_WITH_ALL = "pagination_not_allowed_with_all"
    STICKER_LIBRARY_PAYLOAD_CONTAINS_INVALID_ITEMS = (
        "sticker_library_payload_contains_invalid_items"
    )
    STICKER_NOT_FOUND = "sticker_not_found"
    STICKER_NOT_IN_USER_LIBRARY = "sticker_not_in_user_library"
    UNSUPPORTED_AVATAR_FILE_TYPE = "unsupported_avatar_file_type"
    UNSUPPORTED_MEDIA_ASSET_TYPE = "unsupported_media_asset_type"
    UNSUPPORTED_MEDIA_FILE_EXTENSION = "unsupported_media_file_extension"
    UNSUPPORTED_MEDIA_FILE_TYPE = "unsupported_media_file_type"
    UNSUPPORTED_UPLOAD_MEDIA_TYPE = "unsupported_upload_media_type"

    MESSAGE_NOT_FOUND = "message_not_found"
    NOTIFICATION_NOT_FOUND = "notification_not_found"
    NOTIFICATION_PERMISSION_DENIED = "notification_permission_denied"
    NOTIFICATION_RELATED_FIELDS_INCOMPLETE = "notification_related_fields_incomplete"

    FIELD_NOT_ALLOWED_FOR_SOURCE_TYPE = "field_not_allowed_for_source_type"
    INVALID_HEARTBEAT_ACTION = "invalid_heartbeat_action"
    INVALID_INTEGER_FIELD = "invalid_integer_field"
    INVALID_NUMBER_FIELD = "invalid_number_field"
    INVALID_RESOURCE_HEALTH_STATUS = "invalid_resource_health_status"
    INVALID_SOURCE_TYPE = "invalid_source_type"
    INVALID_STRING_FIELD = "invalid_string_field"
    INVALID_WEBSOCKET_PAYLOAD = "invalid_websocket_payload"
    MISSING_RESOURCE_HEALTH_STATUS = "missing_resource_health_status"
    MISSING_SOURCE_TYPE = "missing_source_type"
    PLAYBACK_RESUME_BLOCKED_BY_STALLING_USERS = (
        "playback_resume_blocked_by_stalling_users"
    )
    REQUEST_VALIDATION_FAILED = "request_validation_failed"
    ROOM_VIDEO_CONTROL_FORBIDDEN = "room_video_control_forbidden"
    ROOM_VIDEO_CONTROL_PERMISSION_DENIED = "room_video_control_permission_denied"
    ROOM_VIDEO_SOURCE_NOT_SET = "room_video_source_not_set"
    UNSUPPORTED_CLIENT_MESSAGE_TYPE = "unsupported_client_message_type"
    UNSUPPORTED_COMMAND_ACTION = "unsupported_command_action"
    UNSUPPORTED_ROOM_COMMAND_ACTION = "unsupported_room_command_action"
    UNSUPPORTED_ROOM_VIDEO_COMMAND_ACTION = "unsupported_room_video_command_action"

    FEEDBACK_NOT_FOUND = "feedback_not_found"
    FEEDBACK_PERMISSION_DENIED = "feedback_permission_denied"
